version: "3.4"

services:

app:
  image: monica
  depends_on:
    - db
  ports:
    - "8200:80"
  environment:
    - APP_KEY=ChangeMeBy32KeyLengthOrGenerated
    - DB_HOST=db
  volumes:
    - ./data:/var/www/html/storage
  restart: unless-stopped

db:
  image: mysql:latest
  command: --default-authentication-plugin=mysql_native_password   
  environment:
    - MYSQL_RANDOM_ROOT_PASSWORD=true
    - MYSQL_DATABASE=monica
    - MYSQL_USER=homestead
    - MYSQL_PASSWORD=secret
  volumes:
    - ./mysql:/var/lib/mysql
  restart: unless-stopped





